server:
      port: 4000
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true 
  service-url:
     defaultZone: httP://localhost:8761/eureka/ 
 instance:
  hostname: localhost 


spring:
 application:
    name: API-GATEWAY
 cloud:
  gateway:
   routes:
     - id: TOURIST-SERVICE 
       uri: lb://TOURIST-SERVICE 
       predicates:
         - Path=/tourist/** 

   